### ISSUE TITLE
Schemas support

### ISSUE THREAD

**Issue by hkroger** [monostream/helmi#20]
Does helmi support custom parameters using OSB schemas? If not, is it on the road map at the moment?

**Comment by adrianliechti** [comment]
I like your question :)

we plan a feature, to allow hints for helmi to create its resource.
as a concrete example: send a parameter to set the hostname/subzone instead of helmiXXXXX. so that ingress rules can apply this and results in something like cassandra01.svc.domain.tld. and yes, then it makes sense to use schema to describe the parameters.

do you have a specific idea how to use the feature - or is it more on an abstract level to provide capacities?

**Comment by hkroger** [comment]
Well, a concrete example would be that we plan to launch a service that needs to access an s3 bucket. And we would need to give that location as a parameter for the service when launching it. And since the UI is fully generated from the OSB catalogs, it would be necessary to provide information about that field already when fetching the catalog. Hence the OSB schemas for service instance creation :)

**Comment by hkroger** [comment]
I'm working on a PR for this.

**Comment by adrianliechti** [comment]
let me spend a beer or two one day :)
